name: Deploy application to live website

on:
  push:
    branches: [master]

jobs:
  app-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Deploy application (Sync files with server)
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        protocol: ftp
        port: 21
        security: loose
        server: ftp.gigawhat.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: src/
        server-dir: GigawhatApp/
        exclude: |       
          **/vars.env
          **/data/database/db.sqlite3
          **/public
          **/tmp
